waypoint_list:
  pose1:
    frame_id: map
    x: 0
    y: 0
    z: 0
    qx: 0
    qy: 0
    qz: 0
    qw: 1
  pose2:
    frame_id: map
    x: -0.5
    y: 1.7
    z: 0
    qx: 0
    qy: 0
    qz: 1
    qw: 0
  pose3:
    frame_id: map
    x: -4
    y: 2.3
    z: 0
    qx: 0
    qy: 0
    qz: 0.707
    qw: 0.707
  pose4:
    frame_id: map
    x: -4.3
    y: 2.5
    z: 0
    qx: 0
    qy: 0
    qz: 0.707
    qw: -0.707